---
# vlans to be used to be defined in global vlans variable
# for a host to have a peer role, state the vlan(s) they are in
# for each vlan, the subnet automatically set = 10.0.<vid>.0/24
# ip = 10.0.<vid>.254/24 is dedicated to the faucet controller
# ip = 10.0.<vid>.253/24 is dedicated to the fbgp controller (exabgp to connect to peers)
# ip = 10.0.<vid>.1 -> x are used for peer
# peers are configured to set up BGP peering with 10.0.<vid>.253
# peers advertise prefixes in the networks variable, appending aspath incremental
#
all:
    children:
        servers:
            vars: 
                experiment_home: "{{ lookup('env', 'HOME') }}/sdiro"
                peer_image: "trungdtbk/quagga:iperf3"
                grcp_addr: 192.168.200.1
                grcp_port: "9999"
                #log_level: info
                log_level: debug
                router_hosts: [ m169, m17c, m17d ]
                vlans:
                    vlan10:
                        id: 10
                    vlan20:
                        id: 20
                    vlan30:
                        id: 30
                    vlan100: # for intradomain
                        id: 100
                    vlan200:
                        id: 200
                    vlan201:
                        id: 201
            hosts:
                m114:
                m162:
                m167:
                m169:
                m17c:
                m17d:
                    ansible_connection: local
        hwswitches:
            hosts:
                atx510:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios
                    ansible_user: manager
                atx930-1:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios
                    ansible_user: manager
                atx930-2:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios
                    ansible_user: manager

