---
# vlans to be used to be defined in global vlans variable
# for a host to have a peer role, state the vlan(s) they are in
# for each vlan, the subnet automatically set = 10.0.<vid>.0/24
# ip = 10.0.<vid>.254/24 is dedicated to the faucet controller
# ip = 10.0.<vid>.253/24 is dedicated to the fbgp controller (exabgp to connect to peers)
# ip = 10.0.<vid>.1 -> x are used for peer
# peers are configured to set up BGP peering with 10.0.<vid>.253
# peers advertise prefixes in the networks variable, appending aspath incremental
#
all:
    children:
        servers:
            vars: 
                experiment_home: "{{ lookup('env', 'HOME') }}/sdiro"
                peer_image: "trungdtbk/quagga:iperf3"
                grcp_addr: 192.168.200.1
                grcp_port: "9999"
                log_level: debug
                vlans:
                    vlan10:
                        id: 10
                    vlan20:
                        id: 20
                    vlan30:
                        id: 30
                    vlan40:
                        id: 40
                    vlan100:
                        id: 100
                        intra: true # for intradomain
                    vlan200:
                        id: 200
            hosts:
                m114:
                m162:
                m167:
                    # take the role of peer
                    phys_intf: enp2s0f0
                    peers:
                        - id: 1
                          asn: 1
                          vlan: vlan30
                          networks: ["1.0.0.0/24", "2.0.0.0/24"]
                        - id: 2
                          asn: 2
                          vlan: vlan30
                          networks: ["2.0.0.0/24"]
                        - id: 3
                          asn: 2
                          vlan: vlan40
                m169:
                    # it will take a role of fbgp router
                    phys_intf: enp2s0f0
                    router_id: 10.0.100.100
                    router_name: router1
                    switch_dpid: 0x0000e01aea17c523
                    interfaces:
                        - vlan: vlan30
                          switch_ports: [10, 12]
                          peers:
                              - id: 1
                                asn: 1
                              - id: 2
                                asn: 2
                        - vlan: vlan40
                          switch_ports: [10, 12]
                          peers:
                              - id: 3
                                asn: 2
                        - vlan: vlan100
                          ip: 10.0.100.100
                          faucet_vips: [ 10.0.100.200 ]
                          switch_ports: [5, 10]
                          peers:
                              - id: 250 # reflector
                                asn: 65000
                    borders:
                        - rid: 10.0.100.101
                          nexthop: 10.0.100.201
                    reflector:
                        id: 250
                        vlan: vlan100
                        clients: [ 10.0.100.100, 10.0.100.101, 10.0.100.102 ]

                m17c:
                    phys_intf: enp1s0f0
                    switch_dpid: 0x0000eccd6d9d4950
                    router_id: 10.0.100.101
                    router_name: router2
                    interfaces:
                        - vlan: vlan100
                          switch_ports: [4, 11]
                          ip: 10.0.100.101
                          faucet_vips: [ 10.0.100.201 ]
                          peers:
                              - id: 250 # reflector
                                asn: 65000
                        - vlan: vlan200
                          switch_ports: [11] 
                          peers:
                              - id: 1
                                asn: 200

                    borders:
                        - rid: 10.0.100.100
                          nexthop: 10.0.100.200
                    peers:
                        - id: 1
                          asn: 200
                          vlan: vlan200

                m17d:
                    ansible_connection: local
        hwswitches:
            hosts:
                atx510:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios
                atx930-1:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios
                atx930-2:
                    ansible_ssh_user: manager
                    ansible_connection: network_cli
                    ansible_network_os: ios

