---

- name: connectivity established
  hosts: m17c
  tasks:
      - name: ping other borders
        command: docker exec -it fbgp_router ping {{ item }} -c 2
        with_items:
            - 10.0.100.101
            - 10.0.100.102
            - 10.0.100.103

      - name: ping from peer_100_1
        command: docker exec -it peer_100_1 ping {{ item }} -c 2
        register: result
        with_items:
            - 1.0.0.1
            - 2.0.0.1
            - 3.0.0.1
            - 4.0.0.1
        retries: 3
        delay: 10

      - name: check ping
        assert:
            that: 
                - "'bytes' in item.stdout"
            fail_msg: "{{ result['results'] | string }}"
            success_msg: "ping all prefixes ok"
            #quiet: yes # not available until 2.8
        loop: "{{ result.results }}"

      #- name: start iperf test

