---

- name: test local connectivity
  hosts: m162
  tasks:
      - name: ping gateway
        shell: docker ps | awk '{ if ($1 != "CONTAINER"){ print $1}}' | while read line; do docker exec $line ping {{item}} -c 2; done
        with_items:
            - 10.0.10.254
            - 10.0.10.253

  hosts: m167
  tasks:
      - name: ping gateway
        shell: docker ps | awk '{ if ($1 != "CONTAINER"){ print $1}}' | while read line; do docker exec $line ping {{item}} -c 2; done
        with_items:
            - 10.0.20.254
            - 10.0.30.254
