
- name: copy config
  copy:
      dest: "{{ experiment_home }}/configs/"
      src: "{{ item }}"
  loop:
      - "./files/gauge.yaml"
      - "./files/faucet-gauge.yaml"
      - "./files/faucet.rules.yml"
  register: gauge_config

- name: create gauge container
  docker_container:
      name: "gauge"
      image: "faucet/gauge"
      hostname: "gauge"
      recreate: "{{ True if gauge_config.changed else omit }}"
      volumes:
          - "{{ experiment_home }}/configs:/etc/faucet"
          - "{{ experiment_home }}/logs:/var/log/faucet"
      ports:
          - "0.0.0.0:6763:6653"

- name: generate prometheus config
  template:
      src: prometheus.j2
      dest: "{{ experiment_home }}/configs/prometheus.yml"
  register: prom_config

- name: create prometheus container
  docker_container:
      name: "prometheus"
      image: "prom/prometheus:v2.9.0"
      recreate: "{{ True if (gauge_config.changed or prom_config.changed) else omit }}"
      user: root
      ports:
          - "9090:9090"
      volumes:
          - "{{ experiment_home }}/configs:/etc/prometheus"
          - "{{ experiment_home }}/prometheus:/prometheus"
      links:
          - gauge

- name: create grafana
  docker_container:
      user: root
      name: "grafana"
      recreate: "{{ True if (gauge_config.changed or prom_config.changed) else omit }}"
      image: "grafana/grafana:5.4.0"
      ports:
          - "3000:3000"
      links:
          - prometheus
      volumes:
          - "{{ experiment_home }}/grafana:/var/lib/grafana"
