
- name: create dirs to store experiment results
  file:
      path: "{{ experiment_home }}/{{ item }}"
      state: directory
      mode: '777'
  with_items:
      - data
      - configs
      - logs
      - mrt_files

- name: allow tcpdump to run without root
  become: yes
  become_user: root
  shell: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
