
- name: create dirs to store experiment results
  file:
      path: "{{ experiment_home }}/{{ item }}"
      state: directory
      mode: '777'
  with_items:
      - data
      - configs
      - logs
      - mrt_files

